[package]
name = "software-joystick"
version = "0.2.0"
authors = ["Kevin Kellar <kellar.kevin@gmail.com>", "Gwilym Kuiper <gw@ilym.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input-linux = "0.5.0"

